### ISSUE TITLE
报错ValueError: cannot find context for 'fork'

### ISSUE THREAD

**Issue by zanshuxun** [guofei9987/scikit-opt#119]
**Describe the bug(问题描述)**
报错ValueError: cannot find context for 'fork'

**To Reproduce(复现步骤)**
1. 将项目下载到本地
2. 运行demo_afsa.py
3. See error.详细报错：
```
D:\programs\Anaconda3\python.exe D:/programs/下载/scikit-opt-master/examples/demo_afsa.py
Traceback (most recent call last):
  File "D:\programs\Anaconda3\lib\multiprocessing\context.py", line 190, in get_context
    ctx = _concrete_contexts[method]
KeyError: 'fork'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/programs/下载/scikit-opt-master/examples/demo_afsa.py", line 6, in <module>
    from sko.AFSA import AFSA
  File "D:\programs\下载\scikit-opt-master\sko\__init__.py", line 3, in <module>
    from . import DE, GA, PSO, SA, ACA, AFSA, IA, tools
  File "D:\programs\下载\scikit-opt-master\sko\DE.py", line 11, in <module>
    from .GA import GeneticAlgorithmBase, GA
  File "D:\programs\下载\scikit-opt-master\sko\GA.py", line 9, in <module>
    from sko.tools import func_transformer
  File "D:\programs\下载\scikit-opt-master\sko\tools.py", line 8, in <module>
    multiprocessing.set_start_method('fork')
  File "D:\programs\Anaconda3\lib\multiprocessing\context.py", line 246, in set_start_method
    self._actual_context = self.get_context(method)
  File "D:\programs\Anaconda3\lib\multiprocessing\context.py", line 238, in get_context
    return super().get_context(method)
  File "D:\programs\Anaconda3\lib\multiprocessing\context.py", line 192, in get_context
    raise ValueError('cannot find context for %r' % method)
ValueError: cannot find context for 'fork'

Process finished with exit code 1

```

**Operating environment(运行环境):**
 - windwos 10
 - python version 3.6
 - numpy 1.19.2
 - scipy version 1.1.0

**Comment by zanshuxun** [comment]
手动将https://github.com/guofei9987/scikit-opt/blob/b1f147af996f9839b7c107c17a8dd8c7098cdef0/sko/tools.py#L8
改为`multiprocessing.set_start_method('spawn')`后可以跑通

**Comment by guofei9987** [comment]
Thank you for reporting this bug. It is very helpful!  

This bug has been fixed in the dev version, and will be released soon.

**Comment by guofei9987** [comment]
New version has been released.
