### ISSUE TITLE
demo_pso_tsp.py运行有误

### ISSUE THREAD

**Issue by a2635814919** [guofei9987/scikit-opt#231]
报错信息为：
invalid escape sequence '\h'

Traceback (most recent call last):
  File "D:\Programs\OA\scikit-opt\examples\demo_pso_tsp.py", line 25, in <module>
    pso_tsp = PSO_TSP(func=cal_total_distance, n_dim=num_points, size_pop=200, max_iter=800, w=0.8, c1=0.1, c2=0.1)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\OA\scikit-opt\sko\PSO.py", line 212, in __init__
    self.func = func_transformer(func)
                ^^^^^^^^^^^^^^^^^^^^^^
TypeError: func_transformer() missing 1 required positional argument: 'n_processes'

**Comment by a2635814919** [comment]
经检查为PSO.py中PSO_TSP类__init__函数中(212行)未对n_processes做初始化，修改为n_processes=0
