### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [guofei9987/scikit-opt#55]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.5.6. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary scikit-opt -w /tmp/ext scikit-opt==0.5.6
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting scikit-opt==0.5.6
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/288/dd1c4e27be972/scikit-opt-0.5.6.tar.gz (22 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-eoj_scqa/scikit-opt/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-eoj_scqa/scikit-opt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-eoj_scqa/scikit-opt/pip-egg-info
         cwd: /tmp/pip-wheel-eoj_scqa/scikit-opt/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-eoj_scqa/scikit-opt/setup.py", line 25, in <module>
        long_description=read_file('docs/en/README.md'),
      File "/tmp/pip-wheel-eoj_scqa/scikit-opt/setup.py", line 10, in read_file
        with open(os_path.join(this_directory, filename), encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-wheel-eoj_scqa/scikit-opt/docs/en/README.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by guofei9987** [comment]
Thank you for this issue.
I did not know sdist. Is it important? Why use `pip install .`?

**Comment by thatch** [comment]
Some companies and distros want to compile everything from source, so pass `--no-binary :all:`, for example https://github.com/dropbox/dbx_build_tools/blob/master/build_tools/py/vpip.py#L311
